export interface ThemePreset {
  id: string;
  name: string;
  category: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  fontFamily: string;
  tagline: string;
  heroTitle: string;
  heroSubtitle: string;
  announcementTicker: string;
  ctaButtonText: string;
}

export const FREE_THEME_PRESETS: ThemePreset[] = [
  {
    id: 'luna-classic',
    name: 'Luna Classic',
    category: 'Official Luna Identity',
    description: 'Intelligence purple and warm cream with energetic tangerine call-to-actions. The official Luna brand look.',
    primaryColor: '#291E29',
    secondaryColor: '#341539',
    accentColor: '#FFA800',
    backgroundColor: '#FFF6E9',
    textColor: '#291E29',
    fontFamily: 'Sora',
    tagline: 'Beyond the Expected · Intelligent Queue & Arrival Management',
    heroTitle: 'Welcome to our Digital Arrival Experience',
    heroSubtitle: 'Reserve a 30-minute priority arrival window or pre-clear your paperwork online before visiting.',
    announcementTicker: 'Live Queue Operating · Zero Walk-in Waiting',
    ctaButtonText: 'Book Timed Ticket',
  },
  {
    id: 'oceanic-cobalt',
    name: 'Oceanic Cobalt',
    category: 'Banking & Financial Trust',
    description: 'Authoritative deep navy, crisp blue, and sky accents designed for banks, wealth advisory, and credit institutions.',
    primaryColor: '#0057B8',
    secondaryColor: '#002F6C',
    accentColor: '#00A3E0',
    backgroundColor: '#F4F8FC',
    textColor: '#0B1D3A',
    fontFamily: 'Inter',
    tagline: 'Secure Branch Banking & Priority Window Reservations',
    heroTitle: 'Smart Branch Banking & Priority Counters',
    heroSubtitle: 'Bypass lobby congestion by reserving a confirmed teller window or opening accounts online.',
    announcementTicker: 'Fast-Track Tellers Live · Average Door-to-Counter 3.5 Mins',
    ctaButtonText: 'Get Priority Window Ticket',
  },
  {
    id: 'emerald-wellness',
    name: 'Emerald Wellness',
    category: 'Healthcare & Clinical Care',
    description: 'Soothing botanical forest green, clinical mint glow, and pure herbal mist for hospitals, diagnostics, and clinics.',
    primaryColor: '#12A05A',
    secondaryColor: '#0E7A44',
    accentColor: '#17B568',
    backgroundColor: '#F3FBF6',
    textColor: '#0A2E1A',
    fontFamily: 'Inter',
    tagline: 'Outpatient Triage & Zero-Crowd Waiting Lounges',
    heroTitle: 'Outpatient Consultation & Diagnostic Triage',
    heroSubtitle: 'Pre-clear medical documents from home and receive real-time SMS alerts when your specialist is ready.',
    announcementTicker: 'Clinical Queues Operating · Real-Time Position Tracking',
    ctaButtonText: 'Book Consultation Window',
  },
  {
    id: 'tangerine-spark',
    name: 'Tangerine Spark',
    category: 'Telecom & High-Speed Retail',
    description: 'High-energy radiant orange, amber gold, and warm cream for flagship tech stores, telecom, and consumer electronics.',
    primaryColor: '#FF8A00',
    secondaryColor: '#D97300',
    accentColor: '#F45B16',
    backgroundColor: '#FFF8F0',
    textColor: '#2E1800',
    fontFamily: 'Inter',
    tagline: 'Device Upgrades, Fiber Support & Express Retail Service',
    heroTitle: 'Retail Hub & Device Upgrade Priority Counters',
    heroSubtitle: 'Instant device upgrades, SIM registration priority, and dedicated high-speed fiber customer care.',
    announcementTicker: 'Flagship Counters Open · Express Pickup Windows Active',
    ctaButtonText: 'Claim Retail Express Ticket',
  },
  {
    id: 'midnight-obsidian',
    name: 'Midnight Obsidian',
    category: 'Modern Fintech & Luxury',
    description: 'Ultra-sleek obsidian noir, titanium slate, and vibrant cyan neon for modern fintech and high-end services.',
    primaryColor: '#0F172A',
    secondaryColor: '#1E293B',
    accentColor: '#38BDF8',
    backgroundColor: '#F8FAFC',
    textColor: '#0F172A',
    fontFamily: 'Inter',
    tagline: 'Next-Generation Seamless Digital Experience',
    heroTitle: 'Frictionless Digital Service & Concierge Arrival',
    heroSubtitle: 'Experience contactless check-in, cryptographic identity pre-clearance, and VIP counter routing.',
    announcementTicker: 'Concierge Desks Live · Express Digital Queue Active',
    ctaButtonText: 'Reserve Concierge Window',
  },
  {
    id: 'crimson-velvet',
    name: 'Crimson Velvet',
    category: 'Hospitality & Dining',
    description: 'Elegant ruby crimson, velvet wine, and golden champagne for hotels, event venues, and gourmet dining.',
    primaryColor: '#BE123C',
    secondaryColor: '#881337',
    accentColor: '#F59E0B',
    backgroundColor: '#FFF1F2',
    textColor: '#4C0519',
    fontFamily: 'Inter',
    tagline: 'Seamless Guest Arrivals & Priority Table Seating',
    heroTitle: 'Guest Check-In & Priority Seating Reservations',
    heroSubtitle: 'Arrive without waiting. Pre-register your party and receive instant confirmation when your table is ready.',
    announcementTicker: 'Dining Lounges Open · Live Seating Queue Operating',
    ctaButtonText: 'Reserve Arrival Window',
  },
  {
    id: 'amethyst-royal',
    name: 'Amethyst Royal',
    category: 'Higher Education & Academics',
    description: 'Deep imperial violet, lavender mist, and luminous gold for universities, student admissions, and colleges.',
    primaryColor: '#6D28D9',
    secondaryColor: '#4C1D95',
    accentColor: '#FBBF24',
    backgroundColor: '#F5F3FF',
    textColor: '#2E1065',
    fontFamily: 'Inter',
    tagline: 'Admissions, Registrar & Student Service Queues',
    heroTitle: 'University Registrar & Academic Services Portal',
    heroSubtitle: 'Upload transcripts, pre-clear registration forms, and schedule your advisor arrival slot.',
    announcementTicker: 'Admissions Counters Live · Zero Lobby Waiting',
    ctaButtonText: 'Book Advisor Window',
  },
  {
    id: 'nordic-teal',
    name: 'Nordic Teal',
    category: 'Government & Public Civic',
    description: 'Arctic teal, deep spruce, and cyber turquoise for government civic centers, licensing, and clean-tech organizations.',
    primaryColor: '#0F766E',
    secondaryColor: '#115E59',
    accentColor: '#06B6D4',
    backgroundColor: '#F0FDFA',
    textColor: '#134E4A',
    fontFamily: 'Inter',
    tagline: 'Citizen Digital Licensing & Document Fast-Track',
    heroTitle: 'Civic Service Center & Document Fast-Track',
    heroSubtitle: 'Pre-verify biometric data, upload identity documents, and skip municipal waiting lines entirely.',
    announcementTicker: 'Civic Counters Operating · Document Fast-Track Live',
    ctaButtonText: 'Get Fast-Track Pass',
  },
];
